import AppKit
import CryptoKit

/// NSPasteboard 내용을 읽어 ClipItem 으로 변환한다. 타입 감지 우선순위: 파일 > 이미지 > 텍스트(링크/컬러 감지).
enum PasteboardReader {

    /// 비밀번호 매니저 등이 표시하는 "수집 금지" 타입 (http://nspasteboard.org 관례)
    private static let skipTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    static func shouldSkip(_ pb: NSPasteboard) -> Bool {
        guard let types = pb.types, !types.isEmpty else { return true }
        return skipTypes.contains(where: types.contains)
    }

    static func capture(from pb: NSPasteboard, blobsDirectory: URL) -> ClipItem? {
        let sourceApp = NSWorkspace.shared.frontmostApplication

        var item = ClipItem(
            id: nil, uuid: UUID().uuidString,
            createdAt: Date(), updatedAt: Date(), deletedAt: nil,
            kind: .text, checksum: "", title: "",
            text: nil, url: nil, colorHex: nil, imagePath: nil, fileURLs: nil,
            sourceAppBundleID: sourceApp?.bundleIdentifier,
            sourceAppName: sourceApp?.localizedName,
            byteSize: 0, boardId: nil, customTitle: nil
        )

        // 1) 파일
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            let paths = urls.map(\.path)
            item.kind = .file
            item.fileURLs = String(data: (try? JSONEncoder().encode(paths)) ?? Data(), encoding: .utf8)
            item.title = urls.map(\.lastPathComponent).joined(separator: ", ")
            item.text = paths.joined(separator: "\n")
            item.checksum = sha256(Data(paths.joined(separator: "\n").utf8))
            item.byteSize = item.text?.utf8.count ?? 0
            return item
        }

        // 2) 이미지 (파일 복사가 아닌 순수 이미지 데이터)
        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            let checksum = sha256(data)
            let path = blobsDirectory.appendingPathComponent("\(checksum).png")
            if !FileManager.default.fileExists(atPath: path.path) {
                let pngData: Data
                if pb.data(forType: .png) != nil {
                    pngData = data
                } else if let rep = NSBitmapImageRep(data: data),
                          let converted = rep.representation(using: .png, properties: [:]) {
                    pngData = converted
                } else {
                    pngData = data
                }
                try? pngData.write(to: path)
            }
            let size = NSImage(data: data)?.size ?? .zero
            item.kind = .image
            item.checksum = checksum
            item.imagePath = path.path
            item.title = "이미지 \(Int(size.width))×\(Int(size.height))"
            item.byteSize = data.count
            return item
        }

        // 3) 텍스트 (링크/컬러 감지 포함)
        if let string = pb.string(forType: .string), !string.isEmpty {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            item.text = string
            item.checksum = sha256(Data(string.utf8))
            item.byteSize = string.utf8.count
            item.title = String(trimmed.split(separator: "\n").first ?? "").prefix(80).description
            if item.title.isEmpty { item.title = "(공백)" }

            if let url = URL(string: trimmed),
               let scheme = url.scheme?.lowercased(), ["http", "https"].contains(scheme),
               trimmed.split(separator: "\n").count == 1 {
                item.kind = .link
                item.url = trimmed
            } else if isColorHex(trimmed) {
                item.kind = .color
                item.colorHex = trimmed.hasPrefix("#") ? trimmed : "#\(trimmed)"
            } else {
                item.kind = .text
            }
            return item
        }

        return nil
    }

    private static func isColorHex(_ s: String) -> Bool {
        let body = s.hasPrefix("#") ? String(s.dropFirst()) : s
        guard [3, 6, 8].contains(body.count), s.hasPrefix("#") || body.count == 6 else { return false }
        return body.allSatisfy(\.isHexDigit)
    }

    private static func sha256(_ data: Data) -> String {
        SHA256.hash(data: data).map { String(format: "%02x", $0) }.joined()
    }
}
